export const APP_CONFIG = {
  APP_NAME: "Audio Guia Rusia",
  PROXY: "/api/",
  SERVER_URL: "http://moscutourgratis.com:8069",
  SERVER_PORT: "8069",
  DATABASE_NAME: "Audio_Guia_Rusia",
  SQLITE_DB: "Audio_Guia_Rusia_23.db",
  URL_PLAY_STORE: "https://play.google.com/store/apps/developer?id:Tour%20Gratis%20Rusia&hl:es",
  EMAIL: "app_admin",
  PASS_EMAIL: "p{R2H[",
  CITY_ID: 1,
  CITY_CODE: "mos_01",
  FOLDER_AUDIO: '', // Environment.getExternalStorageDirectory() + File.separator + "Audio_Guia" + File.separator + CITY_ID + File.separator,
  URL_MAP: "http://moscutourgratis.com:8085/moscu.sqlite",
  // MAILTO : "tourgratisrusia@gmail.com",
  // MAILTO : "budin1992@gmail.com",
  GMT_OFF_SET: 4,
  TIME_REFRESH_DATA: 300000, //5 min
  CODE_TOURGUIA_SHOW: 1010,
  CODE_TOURGUIA_EDIT: 1020,
  CODE_RESERVA_SHOW: 1030,
  CODE_RESERVA_EDIT: 1040,
  CODE_FUTURA_SHOW: 1050,
  CODE_FUTURA_EDIT: 1060,
  LIMIT_SQL: 5
};
